CREATE TABLE poll (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	url VARCHAR(512) NOT NULL,
	name VARCHAR(256) NOT NULL,
	poll_status VARCHAR(16) NOT NULL,
	user VARCHAR(64) NOT NULL,
	created_at TIMESTAMP NOT NULL
);
